name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '0 0 * * *'
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: icepuma/rust-action@master
        with:
          args: cargo audit || true && cargo audit --ignore RUSTSEC-2020-0159 --ignore RUSTSEC-2020-0071
